[project]
name = "qlora-peft"
version = "0.1.0"
description = "Sample project showing how to fine tune your model using QLoRA"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "torch==2.1.2",
    "torchvision==0.16.2",
    "torchaudio==2.1.2",
    "transformers==4.38.2",
    "peft==0.10.0",
    "bitsandbytes==0.43.1",
    "accelerate==0.27.2",
    "datasets",
    "sentencepiece",
    "protobuf",
    "python-dotenv>=1.2.2",
    "triton==2.1.0",
    "trl",
]

[[tool.uv.index]]
name = "pytorch-cu121"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch-cu121" }
torchvision = { index = "pytorch-cu121" }
torchaudio = { index = "pytorch-cu121" }

